name: Bug report
description: Report a bug to help us improve
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs Actual
      placeholder: "Expected:\nActual:"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, Node version, etc."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Errors
      render: shell
    validations:
      required: true
